import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navber from "@/component/Navber";
import Footer from "@/component/Footer";
import { Bounce, ToastContainer } from "react-toastify";

const josefin = Josefin_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "wanderlust",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${josefin.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navber />
        {children}
        <Footer />
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
          transition={Bounce}
        />
      </body>
    </html>
  );
}
